spring.datasource.url=jdbc:mysql://mysql-34d6529-job-portaldb.a.aivencloud.com:16403/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truespring.application.name=job-portal
